<?php
/**
 * OrderShippingApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * OrderShippingApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderShippingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'orderApiV1ManagerCancelShipmentCreate' => [
            'application/json',
        ],
        'orderApiV1ManagerChangeShippingMethodUpdate' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'multipart/form-data',
        ],
        'orderApiV1ManagerReviveShipmentCreate' => [
            'application/json',
            'application/x-www-form-urlencoded',
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation orderApiV1ManagerCancelShipmentCreate
     *
     * Cancel Shipment
     *
     * @param  string $order_uuid order_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerCancelShipmentCreate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MerchantOrderCancelShipmentResponse|\OpenAPI\Client\Model\OrderError|\OpenAPI\Client\Model\OrderError
     */
    public function orderApiV1ManagerCancelShipmentCreate($order_uuid, string $contentType = self::contentTypes['orderApiV1ManagerCancelShipmentCreate'][0])
    {
        list($response) = $this->orderApiV1ManagerCancelShipmentCreateWithHttpInfo($order_uuid, $contentType);
        return $response;
    }

    /**
     * Operation orderApiV1ManagerCancelShipmentCreateWithHttpInfo
     *
     * Cancel Shipment
     *
     * @param  string $order_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerCancelShipmentCreate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MerchantOrderCancelShipmentResponse|\OpenAPI\Client\Model\OrderError|\OpenAPI\Client\Model\OrderError, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderApiV1ManagerCancelShipmentCreateWithHttpInfo($order_uuid, string $contentType = self::contentTypes['orderApiV1ManagerCancelShipmentCreate'][0])
    {
        $request = $this->orderApiV1ManagerCancelShipmentCreateRequest($order_uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MerchantOrderCancelShipmentResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\OrderError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\OrderError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MerchantOrderCancelShipmentResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MerchantOrderCancelShipmentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\OrderError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\OrderError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation orderApiV1ManagerCancelShipmentCreateAsync
     *
     * Cancel Shipment
     *
     * @param  string $order_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerCancelShipmentCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1ManagerCancelShipmentCreateAsync($order_uuid, string $contentType = self::contentTypes['orderApiV1ManagerCancelShipmentCreate'][0])
    {
        return $this->orderApiV1ManagerCancelShipmentCreateAsyncWithHttpInfo($order_uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderApiV1ManagerCancelShipmentCreateAsyncWithHttpInfo
     *
     * Cancel Shipment
     *
     * @param  string $order_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerCancelShipmentCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1ManagerCancelShipmentCreateAsyncWithHttpInfo($order_uuid, string $contentType = self::contentTypes['orderApiV1ManagerCancelShipmentCreate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MerchantOrderCancelShipmentResponse';
        $request = $this->orderApiV1ManagerCancelShipmentCreateRequest($order_uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderApiV1ManagerCancelShipmentCreate'
     *
     * @param  string $order_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerCancelShipmentCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function orderApiV1ManagerCancelShipmentCreateRequest($order_uuid, string $contentType = self::contentTypes['orderApiV1ManagerCancelShipmentCreate'][0])
    {

        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && count($order_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling orderApiV1ManagerCancelShipmentCreate'
            );
        }


        $resourcePath = '/order/api/v1/manager/{order_uuid}/cancel-shipment/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($order_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'order_uuid' . '}',
                ObjectSerializer::toPathValue($order_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderApiV1ManagerChangeShippingMethodUpdate
     *
     * Change Shipping Method
     *
     * @param  string $order_uuid order_uuid (required)
     * @param  \OpenAPI\Client\Model\OrderDetail $order_detail order_detail (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\OrderDetail
     */
    public function orderApiV1ManagerChangeShippingMethodUpdate($order_uuid, $order_detail, string $contentType = self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'][0])
    {
        list($response) = $this->orderApiV1ManagerChangeShippingMethodUpdateWithHttpInfo($order_uuid, $order_detail, $contentType);
        return $response;
    }

    /**
     * Operation orderApiV1ManagerChangeShippingMethodUpdateWithHttpInfo
     *
     * Change Shipping Method
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\OrderDetail $order_detail (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\OrderDetail, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderApiV1ManagerChangeShippingMethodUpdateWithHttpInfo($order_uuid, $order_detail, string $contentType = self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'][0])
    {
        $request = $this->orderApiV1ManagerChangeShippingMethodUpdateRequest($order_uuid, $order_detail, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\OrderDetail',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\OrderDetail',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\OrderDetail',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation orderApiV1ManagerChangeShippingMethodUpdateAsync
     *
     * Change Shipping Method
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\OrderDetail $order_detail (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1ManagerChangeShippingMethodUpdateAsync($order_uuid, $order_detail, string $contentType = self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'][0])
    {
        return $this->orderApiV1ManagerChangeShippingMethodUpdateAsyncWithHttpInfo($order_uuid, $order_detail, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderApiV1ManagerChangeShippingMethodUpdateAsyncWithHttpInfo
     *
     * Change Shipping Method
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\OrderDetail $order_detail (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1ManagerChangeShippingMethodUpdateAsyncWithHttpInfo($order_uuid, $order_detail, string $contentType = self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\OrderDetail';
        $request = $this->orderApiV1ManagerChangeShippingMethodUpdateRequest($order_uuid, $order_detail, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderApiV1ManagerChangeShippingMethodUpdate'
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\OrderDetail $order_detail (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function orderApiV1ManagerChangeShippingMethodUpdateRequest($order_uuid, $order_detail, string $contentType = self::contentTypes['orderApiV1ManagerChangeShippingMethodUpdate'][0])
    {

        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && count($order_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling orderApiV1ManagerChangeShippingMethodUpdate'
            );
        }

        // verify the required parameter 'order_detail' is set
        if ($order_detail === null || (is_array($order_detail) && count($order_detail) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_detail when calling orderApiV1ManagerChangeShippingMethodUpdate'
            );
        }


        $resourcePath = '/order/api/v1/manager/{order_uuid}/change-shipping-method/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($order_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'order_uuid' . '}',
                ObjectSerializer::toPathValue($order_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($order_detail)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($order_detail));
            } else {
                $httpBody = $order_detail;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderApiV1ManagerReviveShipmentCreate
     *
     * Revive Shipment
     *
     * @param  string $order_uuid order_uuid (required)
     * @param  \OpenAPI\Client\Model\ReviveShipment|null $revive_shipment revive_shipment (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerReviveShipmentCreate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MerchantOrderReviveShipmentResponse|\OpenAPI\Client\Model\OrderError|\OpenAPI\Client\Model\OrderError
     */
    public function orderApiV1ManagerReviveShipmentCreate($order_uuid, $revive_shipment = null, string $contentType = self::contentTypes['orderApiV1ManagerReviveShipmentCreate'][0])
    {
        list($response) = $this->orderApiV1ManagerReviveShipmentCreateWithHttpInfo($order_uuid, $revive_shipment, $contentType);
        return $response;
    }

    /**
     * Operation orderApiV1ManagerReviveShipmentCreateWithHttpInfo
     *
     * Revive Shipment
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\ReviveShipment|null $revive_shipment (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerReviveShipmentCreate'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MerchantOrderReviveShipmentResponse|\OpenAPI\Client\Model\OrderError|\OpenAPI\Client\Model\OrderError, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderApiV1ManagerReviveShipmentCreateWithHttpInfo($order_uuid, $revive_shipment = null, string $contentType = self::contentTypes['orderApiV1ManagerReviveShipmentCreate'][0])
    {
        $request = $this->orderApiV1ManagerReviveShipmentCreateRequest($order_uuid, $revive_shipment, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\MerchantOrderReviveShipmentResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\OrderError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\OrderError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\MerchantOrderReviveShipmentResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MerchantOrderReviveShipmentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\OrderError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\OrderError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation orderApiV1ManagerReviveShipmentCreateAsync
     *
     * Revive Shipment
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\ReviveShipment|null $revive_shipment (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerReviveShipmentCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1ManagerReviveShipmentCreateAsync($order_uuid, $revive_shipment = null, string $contentType = self::contentTypes['orderApiV1ManagerReviveShipmentCreate'][0])
    {
        return $this->orderApiV1ManagerReviveShipmentCreateAsyncWithHttpInfo($order_uuid, $revive_shipment, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderApiV1ManagerReviveShipmentCreateAsyncWithHttpInfo
     *
     * Revive Shipment
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\ReviveShipment|null $revive_shipment (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerReviveShipmentCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderApiV1ManagerReviveShipmentCreateAsyncWithHttpInfo($order_uuid, $revive_shipment = null, string $contentType = self::contentTypes['orderApiV1ManagerReviveShipmentCreate'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MerchantOrderReviveShipmentResponse';
        $request = $this->orderApiV1ManagerReviveShipmentCreateRequest($order_uuid, $revive_shipment, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderApiV1ManagerReviveShipmentCreate'
     *
     * @param  string $order_uuid (required)
     * @param  \OpenAPI\Client\Model\ReviveShipment|null $revive_shipment (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['orderApiV1ManagerReviveShipmentCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function orderApiV1ManagerReviveShipmentCreateRequest($order_uuid, $revive_shipment = null, string $contentType = self::contentTypes['orderApiV1ManagerReviveShipmentCreate'][0])
    {

        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && count($order_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling orderApiV1ManagerReviveShipmentCreate'
            );
        }



        $resourcePath = '/order/api/v1/manager/{order_uuid}/revive-shipment/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($order_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'order_uuid' . '}',
                ObjectSerializer::toPathValue($order_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($revive_shipment)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($revive_shipment));
            } else {
                $httpBody = $revive_shipment;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
