<?php
/**
 * ErrorEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ErrorEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;User is not authenticated.&#x60; - کاربر تأیید هویت نشده است. * &#x60;Order not found.&#x60; - Order not found. * &#x60;Order is not in a state where shipping can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * &#x60;Order is not in a state where packing can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * &#x60;Failed to initiate refund. Please try again later.&#x60; - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * &#x60;Order is expired or cancelled.&#x60; - سفارش منقضی‌شده یا لغو‌شده است. * &#x60;Invalid request origin.&#x60; - Invalid request origin. * &#x60;Digi Express shipping method not found.&#x60; - روش ارسال دیجی اکسپرس یافت نشد. * &#x60;Order address not found.&#x60; - آدرس سفارش یافت نشد. * &#x60;Failed to fetch Digi Express shipping time window options.&#x60; - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * &#x60;Address ID not found.&#x60; - Address ID not found. * &#x60;Failed to cancel shipment.&#x60; - خطا در کنسل کردن مرسوله. * &#x60;Failed to cancel shipment in third party service.&#x60; - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * &#x60;Shipment not found.&#x60; - Shipment not found. * &#x60;Selected shipping method is not eligible for cancellation.&#x60; - Selected shipping method is not eligible for cancellation. * &#x60;DigiExpress shipment is not in cancelable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * &#x60;DigiExpress shipment is not in reviveable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * &#x60;Failed to revive shipment in third party service.&#x60; - Failed to revive shipment in third party service. * &#x60;Selected shipping method is not eligible for revival.&#x60; - Selected shipping method is not eligible for revival.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ErrorEnum
{
    /**
     * Possible values of this enum
     */
    public const USER_IS_NOT_AUTHENTICATED = 'User is not authenticated.';

    public const ORDER_NOT_FOUND = 'Order not found.';

    public const ORDER_IS_NOT_IN_A_STATE_WHERE_SHIPPING_CAN_BE_SELECTED = 'Order is not in a state where shipping can be selected.';

    public const ORDER_IS_NOT_IN_A_STATE_WHERE_PACKING_CAN_BE_SELECTED = 'Order is not in a state where packing can be selected.';

    public const FAILED_TO_INITIATE_REFUND__PLEASE_TRY_AGAIN_LATER = 'Failed to initiate refund. Please try again later.';

    public const ORDER_IS_EXPIRED_OR_CANCELLED = 'Order is expired or cancelled.';

    public const INVALID_REQUEST_ORIGIN = 'Invalid request origin.';

    public const DIGI_EXPRESS_SHIPPING_METHOD_NOT_FOUND = 'Digi Express shipping method not found.';

    public const ORDER_ADDRESS_NOT_FOUND = 'Order address not found.';

    public const FAILED_TO_FETCH_DIGI_EXPRESS_SHIPPING_TIME_WINDOW_OPTIONS = 'Failed to fetch Digi Express shipping time window options.';

    public const ADDRESS_ID_NOT_FOUND = 'Address ID not found.';

    public const FAILED_TO_CANCEL_SHIPMENT = 'Failed to cancel shipment.';

    public const FAILED_TO_CANCEL_SHIPMENT_IN_THIRD_PARTY_SERVICE = 'Failed to cancel shipment in third party service.';

    public const SHIPMENT_NOT_FOUND = 'Shipment not found.';

    public const SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_CANCELLATION = 'Selected shipping method is not eligible for cancellation.';

    public const DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_CANCELABLE_IN_THIS_STATE = 'DigiExpress shipment is not in cancelable in this state';

    public const DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_REVIVEABLE_IN_THIS_STATE = 'DigiExpress shipment is not in reviveable in this state';

    public const FAILED_TO_REVIVE_SHIPMENT_IN_THIRD_PARTY_SERVICE = 'Failed to revive shipment in third party service.';

    public const SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_REVIVAL = 'Selected shipping method is not eligible for revival.';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER_IS_NOT_AUTHENTICATED,
            self::ORDER_NOT_FOUND,
            self::ORDER_IS_NOT_IN_A_STATE_WHERE_SHIPPING_CAN_BE_SELECTED,
            self::ORDER_IS_NOT_IN_A_STATE_WHERE_PACKING_CAN_BE_SELECTED,
            self::FAILED_TO_INITIATE_REFUND__PLEASE_TRY_AGAIN_LATER,
            self::ORDER_IS_EXPIRED_OR_CANCELLED,
            self::INVALID_REQUEST_ORIGIN,
            self::DIGI_EXPRESS_SHIPPING_METHOD_NOT_FOUND,
            self::ORDER_ADDRESS_NOT_FOUND,
            self::FAILED_TO_FETCH_DIGI_EXPRESS_SHIPPING_TIME_WINDOW_OPTIONS,
            self::ADDRESS_ID_NOT_FOUND,
            self::FAILED_TO_CANCEL_SHIPMENT,
            self::FAILED_TO_CANCEL_SHIPMENT_IN_THIRD_PARTY_SERVICE,
            self::SHIPMENT_NOT_FOUND,
            self::SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_CANCELLATION,
            self::DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_CANCELABLE_IN_THIS_STATE,
            self::DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_REVIVEABLE_IN_THIS_STATE,
            self::FAILED_TO_REVIVE_SHIPMENT_IN_THIRD_PARTY_SERVICE,
            self::SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_REVIVAL
        ];
    }
}


