<?php
/**
 * OrderCreate
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OrderCreate Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderCreate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'OrderCreate';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'merchant_order_id' => 'string',
        'merchant_unique_id' => 'string',
        'main_amount' => 'int',
        'final_amount' => 'int',
        'total_paid_amount' => 'int',
        'discount_amount' => 'int',
        'tax_amount' => 'int',
        'shipping_amount' => 'int',
        'loyalty_amount' => 'int',
        'callback_url' => 'string',
        'destination_address' => 'mixed',
        'items' => '\OpenAPI\Client\Model\OrderItemCreate[]',
        'merchant' => 'int',
        'source_address' => 'mixed',
        'user' => 'int',
        'reservation_expired_at' => 'int',
        'reference_code' => 'string',
        'preparation_time' => 'int',
        'weight' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'merchant_order_id' => null,
        'merchant_unique_id' => null,
        'main_amount' => null,
        'final_amount' => null,
        'total_paid_amount' => null,
        'discount_amount' => null,
        'tax_amount' => null,
        'shipping_amount' => null,
        'loyalty_amount' => null,
        'callback_url' => 'uri',
        'destination_address' => null,
        'items' => null,
        'merchant' => null,
        'source_address' => null,
        'user' => null,
        'reservation_expired_at' => null,
        'reference_code' => null,
        'preparation_time' => null,
        'weight' => 'double'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'merchant_order_id' => false,
        'merchant_unique_id' => false,
        'main_amount' => false,
        'final_amount' => false,
        'total_paid_amount' => false,
        'discount_amount' => false,
        'tax_amount' => false,
        'shipping_amount' => false,
        'loyalty_amount' => false,
        'callback_url' => false,
        'destination_address' => true,
        'items' => false,
        'merchant' => false,
        'source_address' => true,
        'user' => true,
        'reservation_expired_at' => true,
        'reference_code' => false,
        'preparation_time' => false,
        'weight' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'merchant_order_id' => 'merchant_order_id',
        'merchant_unique_id' => 'merchant_unique_id',
        'main_amount' => 'main_amount',
        'final_amount' => 'final_amount',
        'total_paid_amount' => 'total_paid_amount',
        'discount_amount' => 'discount_amount',
        'tax_amount' => 'tax_amount',
        'shipping_amount' => 'shipping_amount',
        'loyalty_amount' => 'loyalty_amount',
        'callback_url' => 'callback_url',
        'destination_address' => 'destination_address',
        'items' => 'items',
        'merchant' => 'merchant',
        'source_address' => 'source_address',
        'user' => 'user',
        'reservation_expired_at' => 'reservation_expired_at',
        'reference_code' => 'reference_code',
        'preparation_time' => 'preparation_time',
        'weight' => 'weight'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'merchant_order_id' => 'setMerchantOrderId',
        'merchant_unique_id' => 'setMerchantUniqueId',
        'main_amount' => 'setMainAmount',
        'final_amount' => 'setFinalAmount',
        'total_paid_amount' => 'setTotalPaidAmount',
        'discount_amount' => 'setDiscountAmount',
        'tax_amount' => 'setTaxAmount',
        'shipping_amount' => 'setShippingAmount',
        'loyalty_amount' => 'setLoyaltyAmount',
        'callback_url' => 'setCallbackUrl',
        'destination_address' => 'setDestinationAddress',
        'items' => 'setItems',
        'merchant' => 'setMerchant',
        'source_address' => 'setSourceAddress',
        'user' => 'setUser',
        'reservation_expired_at' => 'setReservationExpiredAt',
        'reference_code' => 'setReferenceCode',
        'preparation_time' => 'setPreparationTime',
        'weight' => 'setWeight'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'merchant_order_id' => 'getMerchantOrderId',
        'merchant_unique_id' => 'getMerchantUniqueId',
        'main_amount' => 'getMainAmount',
        'final_amount' => 'getFinalAmount',
        'total_paid_amount' => 'getTotalPaidAmount',
        'discount_amount' => 'getDiscountAmount',
        'tax_amount' => 'getTaxAmount',
        'shipping_amount' => 'getShippingAmount',
        'loyalty_amount' => 'getLoyaltyAmount',
        'callback_url' => 'getCallbackUrl',
        'destination_address' => 'getDestinationAddress',
        'items' => 'getItems',
        'merchant' => 'getMerchant',
        'source_address' => 'getSourceAddress',
        'user' => 'getUser',
        'reservation_expired_at' => 'getReservationExpiredAt',
        'reference_code' => 'getReferenceCode',
        'preparation_time' => 'getPreparationTime',
        'weight' => 'getWeight'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('merchant_order_id', $data ?? [], null);
        $this->setIfExists('merchant_unique_id', $data ?? [], null);
        $this->setIfExists('main_amount', $data ?? [], null);
        $this->setIfExists('final_amount', $data ?? [], null);
        $this->setIfExists('total_paid_amount', $data ?? [], null);
        $this->setIfExists('discount_amount', $data ?? [], null);
        $this->setIfExists('tax_amount', $data ?? [], null);
        $this->setIfExists('shipping_amount', $data ?? [], null);
        $this->setIfExists('loyalty_amount', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('destination_address', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
        $this->setIfExists('merchant', $data ?? [], null);
        $this->setIfExists('source_address', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('reservation_expired_at', $data ?? [], null);
        $this->setIfExists('reference_code', $data ?? [], null);
        $this->setIfExists('preparation_time', $data ?? [], 2);
        $this->setIfExists('weight', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['merchant_order_id'] === null) {
            $invalidProperties[] = "'merchant_order_id' can't be null";
        }
        if ((mb_strlen($this->container['merchant_order_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'merchant_order_id', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['merchant_unique_id'] === null) {
            $invalidProperties[] = "'merchant_unique_id' can't be null";
        }
        if ((mb_strlen($this->container['merchant_unique_id']) > 64)) {
            $invalidProperties[] = "invalid value for 'merchant_unique_id', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['main_amount']) && ($this->container['main_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'main_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['main_amount']) && ($this->container['main_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'main_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['final_amount']) && ($this->container['final_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'final_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['final_amount']) && ($this->container['final_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'final_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['total_paid_amount']) && ($this->container['total_paid_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'total_paid_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['total_paid_amount']) && ($this->container['total_paid_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'total_paid_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['discount_amount']) && ($this->container['discount_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'discount_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['discount_amount']) && ($this->container['discount_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'discount_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['tax_amount']) && ($this->container['tax_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'tax_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['tax_amount']) && ($this->container['tax_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'tax_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['shipping_amount']) && ($this->container['shipping_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'shipping_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['shipping_amount']) && ($this->container['shipping_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'shipping_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['loyalty_amount']) && ($this->container['loyalty_amount'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'loyalty_amount', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['loyalty_amount']) && ($this->container['loyalty_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'loyalty_amount', must be bigger than or equal to 0.";
        }

        if ($this->container['callback_url'] === null) {
            $invalidProperties[] = "'callback_url' can't be null";
        }
        if ((mb_strlen($this->container['callback_url']) > 256)) {
            $invalidProperties[] = "invalid value for 'callback_url', the character length must be smaller than or equal to 256.";
        }

        if ($this->container['destination_address'] === null && !$this->isNullableSetToNull('destination_address')) {
            $invalidProperties[] = "'destination_address' can't be null";
        }
        if ($this->container['items'] === null) {
            $invalidProperties[] = "'items' can't be null";
        }
        if ($this->container['user'] === null && !$this->isNullableSetToNull('user')) {
            $invalidProperties[] = "'user' can't be null";
        }
        if (!is_null($this->container['reservation_expired_at']) && ($this->container['reservation_expired_at'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'reservation_expired_at', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['reservation_expired_at']) && ($this->container['reservation_expired_at'] < 0)) {
            $invalidProperties[] = "invalid value for 'reservation_expired_at', must be bigger than or equal to 0.";
        }

        if ($this->container['reference_code'] === null) {
            $invalidProperties[] = "'reference_code' can't be null";
        }
        if (!is_null($this->container['preparation_time']) && ($this->container['preparation_time'] < 0)) {
            $invalidProperties[] = "invalid value for 'preparation_time', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['weight']) && ($this->container['weight'] < 0)) {
            $invalidProperties[] = "invalid value for 'weight', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets merchant_order_id
     *
     * @return string
     */
    public function getMerchantOrderId()
    {
        return $this->container['merchant_order_id'];
    }

    /**
     * Sets merchant_order_id
     *
     * @param string $merchant_order_id شناسه منحصر به فرد این سفارش در سیستم فروشنده
     *
     * @return self
     */
    public function setMerchantOrderId($merchant_order_id)
    {
        if (is_null($merchant_order_id)) {
            throw new \InvalidArgumentException('non-nullable merchant_order_id cannot be null');
        }
        if ((mb_strlen($merchant_order_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $merchant_order_id when calling OrderCreate., must be smaller than or equal to 64.');
        }

        $this->container['merchant_order_id'] = $merchant_order_id;

        return $this;
    }

    /**
     * Gets merchant_unique_id
     *
     * @return string
     */
    public function getMerchantUniqueId()
    {
        return $this->container['merchant_unique_id'];
    }

    /**
     * Sets merchant_unique_id
     *
     * @param string $merchant_unique_id شناسه منحصر به فرد برای تأیید اصالت سفارش
     *
     * @return self
     */
    public function setMerchantUniqueId($merchant_unique_id)
    {
        if (is_null($merchant_unique_id)) {
            throw new \InvalidArgumentException('non-nullable merchant_unique_id cannot be null');
        }
        if ((mb_strlen($merchant_unique_id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $merchant_unique_id when calling OrderCreate., must be smaller than or equal to 64.');
        }

        $this->container['merchant_unique_id'] = $merchant_unique_id;

        return $this;
    }

    /**
     * Gets main_amount
     *
     * @return int|null
     */
    public function getMainAmount()
    {
        return $this->container['main_amount'];
    }

    /**
     * Sets main_amount
     *
     * @param int|null $main_amount مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)
     *
     * @return self
     */
    public function setMainAmount($main_amount)
    {
        if (is_null($main_amount)) {
            throw new \InvalidArgumentException('non-nullable main_amount cannot be null');
        }

        if (($main_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $main_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($main_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $main_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['main_amount'] = $main_amount;

        return $this;
    }

    /**
     * Gets final_amount
     *
     * @return int|null
     */
    public function getFinalAmount()
    {
        return $this->container['final_amount'];
    }

    /**
     * Sets final_amount
     *
     * @param int|null $final_amount مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
     *
     * @return self
     */
    public function setFinalAmount($final_amount)
    {
        if (is_null($final_amount)) {
            throw new \InvalidArgumentException('non-nullable final_amount cannot be null');
        }

        if (($final_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $final_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($final_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $final_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['final_amount'] = $final_amount;

        return $this;
    }

    /**
     * Gets total_paid_amount
     *
     * @return int|null
     */
    public function getTotalPaidAmount()
    {
        return $this->container['total_paid_amount'];
    }

    /**
     * Sets total_paid_amount
     *
     * @param int|null $total_paid_amount مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
     *
     * @return self
     */
    public function setTotalPaidAmount($total_paid_amount)
    {
        if (is_null($total_paid_amount)) {
            throw new \InvalidArgumentException('non-nullable total_paid_amount cannot be null');
        }

        if (($total_paid_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $total_paid_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($total_paid_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $total_paid_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['total_paid_amount'] = $total_paid_amount;

        return $this;
    }

    /**
     * Gets discount_amount
     *
     * @return int|null
     */
    public function getDiscountAmount()
    {
        return $this->container['discount_amount'];
    }

    /**
     * Sets discount_amount
     *
     * @param int|null $discount_amount مبلغ کل تخفیف برای تمام سفارش (به تومان)
     *
     * @return self
     */
    public function setDiscountAmount($discount_amount)
    {
        if (is_null($discount_amount)) {
            throw new \InvalidArgumentException('non-nullable discount_amount cannot be null');
        }

        if (($discount_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $discount_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($discount_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $discount_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['discount_amount'] = $discount_amount;

        return $this;
    }

    /**
     * Gets tax_amount
     *
     * @return int|null
     */
    public function getTaxAmount()
    {
        return $this->container['tax_amount'];
    }

    /**
     * Sets tax_amount
     *
     * @param int|null $tax_amount مبلغ کل مالیات برای تمام سفارش (به تومان)
     *
     * @return self
     */
    public function setTaxAmount($tax_amount)
    {
        if (is_null($tax_amount)) {
            throw new \InvalidArgumentException('non-nullable tax_amount cannot be null');
        }

        if (($tax_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $tax_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($tax_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $tax_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['tax_amount'] = $tax_amount;

        return $this;
    }

    /**
     * Gets shipping_amount
     *
     * @return int|null
     */
    public function getShippingAmount()
    {
        return $this->container['shipping_amount'];
    }

    /**
     * Sets shipping_amount
     *
     * @param int|null $shipping_amount هزینه ارسال برای سفارش (به تومان)
     *
     * @return self
     */
    public function setShippingAmount($shipping_amount)
    {
        if (is_null($shipping_amount)) {
            throw new \InvalidArgumentException('non-nullable shipping_amount cannot be null');
        }

        if (($shipping_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $shipping_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($shipping_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $shipping_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['shipping_amount'] = $shipping_amount;

        return $this;
    }

    /**
     * Gets loyalty_amount
     *
     * @return int|null
     */
    public function getLoyaltyAmount()
    {
        return $this->container['loyalty_amount'];
    }

    /**
     * Sets loyalty_amount
     *
     * @param int|null $loyalty_amount مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)
     *
     * @return self
     */
    public function setLoyaltyAmount($loyalty_amount)
    {
        if (is_null($loyalty_amount)) {
            throw new \InvalidArgumentException('non-nullable loyalty_amount cannot be null');
        }

        if (($loyalty_amount > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $loyalty_amount when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (($loyalty_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $loyalty_amount when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['loyalty_amount'] = $loyalty_amount;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string $callback_url آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            throw new \InvalidArgumentException('non-nullable callback_url cannot be null');
        }
        if ((mb_strlen($callback_url) > 256)) {
            throw new \InvalidArgumentException('invalid length for $callback_url when calling OrderCreate., must be smaller than or equal to 256.');
        }

        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets destination_address
     *
     * @return mixed|null
     */
    public function getDestinationAddress()
    {
        return $this->container['destination_address'];
    }

    /**
     * Sets destination_address
     *
     * @param mixed|null $destination_address destination_address
     *
     * @return self
     */
    public function setDestinationAddress($destination_address)
    {
        if (is_null($destination_address)) {
            array_push($this->openAPINullablesSetToNull, 'destination_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('destination_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['destination_address'] = $destination_address;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \OpenAPI\Client\Model\OrderItemCreate[]
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \OpenAPI\Client\Model\OrderItemCreate[] $items items
     *
     * @return self
     */
    public function setItems($items)
    {
        if (is_null($items)) {
            throw new \InvalidArgumentException('non-nullable items cannot be null');
        }
        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Gets merchant
     *
     * @return int|null
     */
    public function getMerchant()
    {
        return $this->container['merchant'];
    }

    /**
     * Sets merchant
     *
     * @param int|null $merchant مقدار توسط سیستم جایگذاری می شود
     *
     * @return self
     */
    public function setMerchant($merchant)
    {
        if (is_null($merchant)) {
            throw new \InvalidArgumentException('non-nullable merchant cannot be null');
        }
        $this->container['merchant'] = $merchant;

        return $this;
    }

    /**
     * Gets source_address
     *
     * @return mixed|null
     */
    public function getSourceAddress()
    {
        return $this->container['source_address'];
    }

    /**
     * Sets source_address
     *
     * @param mixed|null $source_address مقدار توسط سیستم جایگذاری می شود
     *
     * @return self
     */
    public function setSourceAddress($source_address)
    {
        if (is_null($source_address)) {
            array_push($this->openAPINullablesSetToNull, 'source_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source_address'] = $source_address;

        return $this;
    }

    /**
     * Gets user
     *
     * @return int|null
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param int|null $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            array_push($this->openAPINullablesSetToNull, 'user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets reservation_expired_at
     *
     * @return int|null
     */
    public function getReservationExpiredAt()
    {
        return $this->container['reservation_expired_at'];
    }

    /**
     * Sets reservation_expired_at
     *
     * @param int|null $reservation_expired_at مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش
     *
     * @return self
     */
    public function setReservationExpiredAt($reservation_expired_at)
    {
        if (is_null($reservation_expired_at)) {
            array_push($this->openAPINullablesSetToNull, 'reservation_expired_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reservation_expired_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($reservation_expired_at) && ($reservation_expired_at > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $reservation_expired_at when calling OrderCreate., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($reservation_expired_at) && ($reservation_expired_at < 0)) {
            throw new \InvalidArgumentException('invalid value for $reservation_expired_at when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['reservation_expired_at'] = $reservation_expired_at;

        return $this;
    }

    /**
     * Gets reference_code
     *
     * @return string
     */
    public function getReferenceCode()
    {
        return $this->container['reference_code'];
    }

    /**
     * Sets reference_code
     *
     * @param string $reference_code کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
     *
     * @return self
     */
    public function setReferenceCode($reference_code)
    {
        if (is_null($reference_code)) {
            throw new \InvalidArgumentException('non-nullable reference_code cannot be null');
        }
        $this->container['reference_code'] = $reference_code;

        return $this;
    }

    /**
     * Gets preparation_time
     *
     * @return int|null
     */
    public function getPreparationTime()
    {
        return $this->container['preparation_time'];
    }

    /**
     * Sets preparation_time
     *
     * @param int|null $preparation_time Preparation time for the order (in days)
     *
     * @return self
     */
    public function setPreparationTime($preparation_time)
    {
        if (is_null($preparation_time)) {
            throw new \InvalidArgumentException('non-nullable preparation_time cannot be null');
        }

        if (($preparation_time < 0)) {
            throw new \InvalidArgumentException('invalid value for $preparation_time when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['preparation_time'] = $preparation_time;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return float|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param float|null $weight Total Weight of the order (in grams)
     *
     * @return self
     */
    public function setWeight($weight)
    {
        if (is_null($weight)) {
            throw new \InvalidArgumentException('non-nullable weight cannot be null');
        }

        if (($weight < 0)) {
            throw new \InvalidArgumentException('invalid value for $weight when calling OrderCreate., must be bigger than or equal to 0.');
        }

        $this->container['weight'] = $weight;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


