<?php
/**
 * PaymentOrder
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PaymentOrder Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentOrder implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PaymentOrder';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'final_amount' => 'int',
        'gateway_type' => '\OpenAPI\Client\Model\GatewayTypeEnum',
        'gateway_type_display' => 'string',
        'paid_at' => 'string',
        'gateway_name' => 'string',
        'invoice_id' => 'string',
        'settlement_date' => 'string',
        'settlement_status' => 'int',
        'settlement_status_display' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'final_amount' => null,
        'gateway_type' => null,
        'gateway_type_display' => null,
        'paid_at' => null,
        'gateway_name' => null,
        'invoice_id' => null,
        'settlement_date' => null,
        'settlement_status' => null,
        'settlement_status_display' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'final_amount' => false,
        'gateway_type' => false,
        'gateway_type_display' => false,
        'paid_at' => false,
        'gateway_name' => true,
        'invoice_id' => true,
        'settlement_date' => false,
        'settlement_status' => false,
        'settlement_status_display' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'final_amount' => 'final_amount',
        'gateway_type' => 'gateway_type',
        'gateway_type_display' => 'gateway_type_display',
        'paid_at' => 'paid_at',
        'gateway_name' => 'gateway_name',
        'invoice_id' => 'invoice_id',
        'settlement_date' => 'settlement_date',
        'settlement_status' => 'settlement_status',
        'settlement_status_display' => 'settlement_status_display'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'final_amount' => 'setFinalAmount',
        'gateway_type' => 'setGatewayType',
        'gateway_type_display' => 'setGatewayTypeDisplay',
        'paid_at' => 'setPaidAt',
        'gateway_name' => 'setGatewayName',
        'invoice_id' => 'setInvoiceId',
        'settlement_date' => 'setSettlementDate',
        'settlement_status' => 'setSettlementStatus',
        'settlement_status_display' => 'setSettlementStatusDisplay'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'final_amount' => 'getFinalAmount',
        'gateway_type' => 'getGatewayType',
        'gateway_type_display' => 'getGatewayTypeDisplay',
        'paid_at' => 'getPaidAt',
        'gateway_name' => 'getGatewayName',
        'invoice_id' => 'getInvoiceId',
        'settlement_date' => 'getSettlementDate',
        'settlement_status' => 'getSettlementStatus',
        'settlement_status_display' => 'getSettlementStatusDisplay'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('final_amount', $data ?? [], null);
        $this->setIfExists('gateway_type', $data ?? [], null);
        $this->setIfExists('gateway_type_display', $data ?? [], null);
        $this->setIfExists('paid_at', $data ?? [], null);
        $this->setIfExists('gateway_name', $data ?? [], null);
        $this->setIfExists('invoice_id', $data ?? [], null);
        $this->setIfExists('settlement_date', $data ?? [], null);
        $this->setIfExists('settlement_status', $data ?? [], null);
        $this->setIfExists('settlement_status_display', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['final_amount'] === null) {
            $invalidProperties[] = "'final_amount' can't be null";
        }
        if ($this->container['gateway_type'] === null) {
            $invalidProperties[] = "'gateway_type' can't be null";
        }
        if ($this->container['gateway_type_display'] === null) {
            $invalidProperties[] = "'gateway_type_display' can't be null";
        }
        if ($this->container['paid_at'] === null) {
            $invalidProperties[] = "'paid_at' can't be null";
        }
        if ($this->container['gateway_name'] === null && !$this->isNullableSetToNull('gateway_name')) {
            $invalidProperties[] = "'gateway_name' can't be null";
        }
        if ($this->container['invoice_id'] === null && !$this->isNullableSetToNull('invoice_id')) {
            $invalidProperties[] = "'invoice_id' can't be null";
        }
        if ($this->container['settlement_date'] === null) {
            $invalidProperties[] = "'settlement_date' can't be null";
        }
        if ($this->container['settlement_status'] === null) {
            $invalidProperties[] = "'settlement_status' can't be null";
        }
        if ($this->container['settlement_status_display'] === null) {
            $invalidProperties[] = "'settlement_status_display' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets final_amount
     *
     * @return int
     */
    public function getFinalAmount()
    {
        return $this->container['final_amount'];
    }

    /**
     * Sets final_amount
     *
     * @param int $final_amount final_amount
     *
     * @return self
     */
    public function setFinalAmount($final_amount)
    {
        if (is_null($final_amount)) {
            throw new \InvalidArgumentException('non-nullable final_amount cannot be null');
        }
        $this->container['final_amount'] = $final_amount;

        return $this;
    }

    /**
     * Gets gateway_type
     *
     * @return \OpenAPI\Client\Model\GatewayTypeEnum
     */
    public function getGatewayType()
    {
        return $this->container['gateway_type'];
    }

    /**
     * Sets gateway_type
     *
     * @param \OpenAPI\Client\Model\GatewayTypeEnum $gateway_type gateway_type
     *
     * @return self
     */
    public function setGatewayType($gateway_type)
    {
        if (is_null($gateway_type)) {
            throw new \InvalidArgumentException('non-nullable gateway_type cannot be null');
        }
        $this->container['gateway_type'] = $gateway_type;

        return $this;
    }

    /**
     * Gets gateway_type_display
     *
     * @return string
     */
    public function getGatewayTypeDisplay()
    {
        return $this->container['gateway_type_display'];
    }

    /**
     * Sets gateway_type_display
     *
     * @param string $gateway_type_display gateway_type_display
     *
     * @return self
     */
    public function setGatewayTypeDisplay($gateway_type_display)
    {
        if (is_null($gateway_type_display)) {
            throw new \InvalidArgumentException('non-nullable gateway_type_display cannot be null');
        }
        $this->container['gateway_type_display'] = $gateway_type_display;

        return $this;
    }

    /**
     * Gets paid_at
     *
     * @return string
     */
    public function getPaidAt()
    {
        return $this->container['paid_at'];
    }

    /**
     * Sets paid_at
     *
     * @param string $paid_at paid_at
     *
     * @return self
     */
    public function setPaidAt($paid_at)
    {
        if (is_null($paid_at)) {
            throw new \InvalidArgumentException('non-nullable paid_at cannot be null');
        }
        $this->container['paid_at'] = $paid_at;

        return $this;
    }

    /**
     * Gets gateway_name
     *
     * @return string|null
     */
    public function getGatewayName()
    {
        return $this->container['gateway_name'];
    }

    /**
     * Sets gateway_name
     *
     * @param string|null $gateway_name gateway_name
     *
     * @return self
     */
    public function setGatewayName($gateway_name)
    {
        if (is_null($gateway_name)) {
            array_push($this->openAPINullablesSetToNull, 'gateway_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gateway_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gateway_name'] = $gateway_name;

        return $this;
    }

    /**
     * Gets invoice_id
     *
     * @return string|null
     */
    public function getInvoiceId()
    {
        return $this->container['invoice_id'];
    }

    /**
     * Sets invoice_id
     *
     * @param string|null $invoice_id invoice_id
     *
     * @return self
     */
    public function setInvoiceId($invoice_id)
    {
        if (is_null($invoice_id)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_id'] = $invoice_id;

        return $this;
    }

    /**
     * Gets settlement_date
     *
     * @return string
     */
    public function getSettlementDate()
    {
        return $this->container['settlement_date'];
    }

    /**
     * Sets settlement_date
     *
     * @param string $settlement_date settlement_date
     *
     * @return self
     */
    public function setSettlementDate($settlement_date)
    {
        if (is_null($settlement_date)) {
            throw new \InvalidArgumentException('non-nullable settlement_date cannot be null');
        }
        $this->container['settlement_date'] = $settlement_date;

        return $this;
    }

    /**
     * Gets settlement_status
     *
     * @return int
     */
    public function getSettlementStatus()
    {
        return $this->container['settlement_status'];
    }

    /**
     * Sets settlement_status
     *
     * @param int $settlement_status settlement_status
     *
     * @return self
     */
    public function setSettlementStatus($settlement_status)
    {
        if (is_null($settlement_status)) {
            throw new \InvalidArgumentException('non-nullable settlement_status cannot be null');
        }
        $this->container['settlement_status'] = $settlement_status;

        return $this;
    }

    /**
     * Gets settlement_status_display
     *
     * @return string
     */
    public function getSettlementStatusDisplay()
    {
        return $this->container['settlement_status_display'];
    }

    /**
     * Sets settlement_status_display
     *
     * @param string $settlement_status_display settlement_status_display
     *
     * @return self
     */
    public function setSettlementStatusDisplay($settlement_status_display)
    {
        if (is_null($settlement_status_display)) {
            throw new \InvalidArgumentException('non-nullable settlement_status_display cannot be null');
        }
        $this->container['settlement_status_display'] = $settlement_status_display;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


