<?php
/**
 * ShippingMethod
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShippingMethod Class Doc Comment
 *
 * @category Class
 * @description Serializer for shipping method details.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShippingMethod implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ShippingMethod';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'description' => 'string',
        'shipping_type' => '\OpenAPI\Client\Model\ShippingTypeEnum',
        'get_shipping_type_display' => 'string',
        'shipping_type_display' => 'string',
        'cost' => 'int',
        'secondary_cost' => 'int',
        'minimum_time_sending' => 'int',
        'maximum_time_sending' => 'int',
        'delivery_time_display' => 'string',
        'delivery_time_range_display' => '\OpenAPI\Client\Model\DeliveryTimeRangeDisplay',
        'inventory_address' => '\OpenAPI\Client\Model\BusinessAddress',
        'is_pay_at_destination' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'description' => null,
        'shipping_type' => null,
        'get_shipping_type_display' => null,
        'shipping_type_display' => null,
        'cost' => null,
        'secondary_cost' => null,
        'minimum_time_sending' => null,
        'maximum_time_sending' => null,
        'delivery_time_display' => null,
        'delivery_time_range_display' => null,
        'inventory_address' => null,
        'is_pay_at_destination' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => false,
        'shipping_type' => false,
        'get_shipping_type_display' => false,
        'shipping_type_display' => false,
        'cost' => false,
        'secondary_cost' => false,
        'minimum_time_sending' => false,
        'maximum_time_sending' => false,
        'delivery_time_display' => false,
        'delivery_time_range_display' => false,
        'inventory_address' => false,
        'is_pay_at_destination' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'shipping_type' => 'shipping_type',
        'get_shipping_type_display' => 'get_shipping_type_display',
        'shipping_type_display' => 'shipping_type_display',
        'cost' => 'cost',
        'secondary_cost' => 'secondary_cost',
        'minimum_time_sending' => 'minimum_time_sending',
        'maximum_time_sending' => 'maximum_time_sending',
        'delivery_time_display' => 'delivery_time_display',
        'delivery_time_range_display' => 'delivery_time_range_display',
        'inventory_address' => 'inventory_address',
        'is_pay_at_destination' => 'is_pay_at_destination'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'shipping_type' => 'setShippingType',
        'get_shipping_type_display' => 'setGetShippingTypeDisplay',
        'shipping_type_display' => 'setShippingTypeDisplay',
        'cost' => 'setCost',
        'secondary_cost' => 'setSecondaryCost',
        'minimum_time_sending' => 'setMinimumTimeSending',
        'maximum_time_sending' => 'setMaximumTimeSending',
        'delivery_time_display' => 'setDeliveryTimeDisplay',
        'delivery_time_range_display' => 'setDeliveryTimeRangeDisplay',
        'inventory_address' => 'setInventoryAddress',
        'is_pay_at_destination' => 'setIsPayAtDestination'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'shipping_type' => 'getShippingType',
        'get_shipping_type_display' => 'getGetShippingTypeDisplay',
        'shipping_type_display' => 'getShippingTypeDisplay',
        'cost' => 'getCost',
        'secondary_cost' => 'getSecondaryCost',
        'minimum_time_sending' => 'getMinimumTimeSending',
        'maximum_time_sending' => 'getMaximumTimeSending',
        'delivery_time_display' => 'getDeliveryTimeDisplay',
        'delivery_time_range_display' => 'getDeliveryTimeRangeDisplay',
        'inventory_address' => 'getInventoryAddress',
        'is_pay_at_destination' => 'getIsPayAtDestination'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('shipping_type', $data ?? [], null);
        $this->setIfExists('get_shipping_type_display', $data ?? [], null);
        $this->setIfExists('shipping_type_display', $data ?? [], null);
        $this->setIfExists('cost', $data ?? [], null);
        $this->setIfExists('secondary_cost', $data ?? [], null);
        $this->setIfExists('minimum_time_sending', $data ?? [], null);
        $this->setIfExists('maximum_time_sending', $data ?? [], null);
        $this->setIfExists('delivery_time_display', $data ?? [], null);
        $this->setIfExists('delivery_time_range_display', $data ?? [], null);
        $this->setIfExists('inventory_address', $data ?? [], null);
        $this->setIfExists('is_pay_at_destination', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 64)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['get_shipping_type_display'] === null) {
            $invalidProperties[] = "'get_shipping_type_display' can't be null";
        }
        if ($this->container['shipping_type_display'] === null) {
            $invalidProperties[] = "'shipping_type_display' can't be null";
        }
        if (!is_null($this->container['cost']) && ($this->container['cost'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'cost', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['cost']) && ($this->container['cost'] < 0)) {
            $invalidProperties[] = "invalid value for 'cost', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['secondary_cost']) && ($this->container['secondary_cost'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'secondary_cost', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['secondary_cost']) && ($this->container['secondary_cost'] < 0)) {
            $invalidProperties[] = "invalid value for 'secondary_cost', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['minimum_time_sending']) && ($this->container['minimum_time_sending'] > 32767)) {
            $invalidProperties[] = "invalid value for 'minimum_time_sending', must be smaller than or equal to 32767.";
        }

        if (!is_null($this->container['minimum_time_sending']) && ($this->container['minimum_time_sending'] < 0)) {
            $invalidProperties[] = "invalid value for 'minimum_time_sending', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['maximum_time_sending']) && ($this->container['maximum_time_sending'] > 32767)) {
            $invalidProperties[] = "invalid value for 'maximum_time_sending', must be smaller than or equal to 32767.";
        }

        if (!is_null($this->container['maximum_time_sending']) && ($this->container['maximum_time_sending'] < 0)) {
            $invalidProperties[] = "invalid value for 'maximum_time_sending', must be bigger than or equal to 0.";
        }

        if ($this->container['delivery_time_display'] === null) {
            $invalidProperties[] = "'delivery_time_display' can't be null";
        }
        if ($this->container['delivery_time_range_display'] === null) {
            $invalidProperties[] = "'delivery_time_range_display' can't be null";
        }
        if ($this->container['inventory_address'] === null) {
            $invalidProperties[] = "'inventory_address' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name نام روش ارسال
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 64)) {
            throw new \InvalidArgumentException('invalid length for $name when calling ShippingMethod., must be smaller than or equal to 64.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description توضیحات روش ارسال و جزئیات تحویل آن
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets shipping_type
     *
     * @return \OpenAPI\Client\Model\ShippingTypeEnum|null
     */
    public function getShippingType()
    {
        return $this->container['shipping_type'];
    }

    /**
     * Sets shipping_type
     *
     * @param \OpenAPI\Client\Model\ShippingTypeEnum|null $shipping_type نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس
     *
     * @return self
     */
    public function setShippingType($shipping_type)
    {
        if (is_null($shipping_type)) {
            throw new \InvalidArgumentException('non-nullable shipping_type cannot be null');
        }
        $this->container['shipping_type'] = $shipping_type;

        return $this;
    }

    /**
     * Gets get_shipping_type_display
     *
     * @return string
     */
    public function getGetShippingTypeDisplay()
    {
        return $this->container['get_shipping_type_display'];
    }

    /**
     * Sets get_shipping_type_display
     *
     * @param string $get_shipping_type_display get_shipping_type_display
     *
     * @return self
     */
    public function setGetShippingTypeDisplay($get_shipping_type_display)
    {
        if (is_null($get_shipping_type_display)) {
            throw new \InvalidArgumentException('non-nullable get_shipping_type_display cannot be null');
        }
        $this->container['get_shipping_type_display'] = $get_shipping_type_display;

        return $this;
    }

    /**
     * Gets shipping_type_display
     *
     * @return string
     */
    public function getShippingTypeDisplay()
    {
        return $this->container['shipping_type_display'];
    }

    /**
     * Sets shipping_type_display
     *
     * @param string $shipping_type_display shipping_type_display
     *
     * @return self
     */
    public function setShippingTypeDisplay($shipping_type_display)
    {
        if (is_null($shipping_type_display)) {
            throw new \InvalidArgumentException('non-nullable shipping_type_display cannot be null');
        }
        $this->container['shipping_type_display'] = $shipping_type_display;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return int|null
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param int|null $cost هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان
     *
     * @return self
     */
    public function setCost($cost)
    {
        if (is_null($cost)) {
            throw new \InvalidArgumentException('non-nullable cost cannot be null');
        }

        if (($cost > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $cost when calling ShippingMethod., must be smaller than or equal to 2147483647.');
        }
        if (($cost < 0)) {
            throw new \InvalidArgumentException('invalid value for $cost when calling ShippingMethod., must be bigger than or equal to 0.');
        }

        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets secondary_cost
     *
     * @return int|null
     */
    public function getSecondaryCost()
    {
        return $this->container['secondary_cost'];
    }

    /**
     * Sets secondary_cost
     *
     * @param int|null $secondary_cost هزینه ارسال برای مناطق دیگر به تومان
     *
     * @return self
     */
    public function setSecondaryCost($secondary_cost)
    {
        if (is_null($secondary_cost)) {
            throw new \InvalidArgumentException('non-nullable secondary_cost cannot be null');
        }

        if (($secondary_cost > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $secondary_cost when calling ShippingMethod., must be smaller than or equal to 2147483647.');
        }
        if (($secondary_cost < 0)) {
            throw new \InvalidArgumentException('invalid value for $secondary_cost when calling ShippingMethod., must be bigger than or equal to 0.');
        }

        $this->container['secondary_cost'] = $secondary_cost;

        return $this;
    }

    /**
     * Gets minimum_time_sending
     *
     * @return int|null
     */
    public function getMinimumTimeSending()
    {
        return $this->container['minimum_time_sending'];
    }

    /**
     * Sets minimum_time_sending
     *
     * @param int|null $minimum_time_sending حداقل تعداد روزها از تاریخ سفارش تا تحویل
     *
     * @return self
     */
    public function setMinimumTimeSending($minimum_time_sending)
    {
        if (is_null($minimum_time_sending)) {
            throw new \InvalidArgumentException('non-nullable minimum_time_sending cannot be null');
        }

        if (($minimum_time_sending > 32767)) {
            throw new \InvalidArgumentException('invalid value for $minimum_time_sending when calling ShippingMethod., must be smaller than or equal to 32767.');
        }
        if (($minimum_time_sending < 0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_time_sending when calling ShippingMethod., must be bigger than or equal to 0.');
        }

        $this->container['minimum_time_sending'] = $minimum_time_sending;

        return $this;
    }

    /**
     * Gets maximum_time_sending
     *
     * @return int|null
     */
    public function getMaximumTimeSending()
    {
        return $this->container['maximum_time_sending'];
    }

    /**
     * Sets maximum_time_sending
     *
     * @param int|null $maximum_time_sending حداکثر تعداد روزها از تاریخ سفارش تا تحویل
     *
     * @return self
     */
    public function setMaximumTimeSending($maximum_time_sending)
    {
        if (is_null($maximum_time_sending)) {
            throw new \InvalidArgumentException('non-nullable maximum_time_sending cannot be null');
        }

        if (($maximum_time_sending > 32767)) {
            throw new \InvalidArgumentException('invalid value for $maximum_time_sending when calling ShippingMethod., must be smaller than or equal to 32767.');
        }
        if (($maximum_time_sending < 0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_time_sending when calling ShippingMethod., must be bigger than or equal to 0.');
        }

        $this->container['maximum_time_sending'] = $maximum_time_sending;

        return $this;
    }

    /**
     * Gets delivery_time_display
     *
     * @return string
     */
    public function getDeliveryTimeDisplay()
    {
        return $this->container['delivery_time_display'];
    }

    /**
     * Sets delivery_time_display
     *
     * @param string $delivery_time_display delivery_time_display
     *
     * @return self
     */
    public function setDeliveryTimeDisplay($delivery_time_display)
    {
        if (is_null($delivery_time_display)) {
            throw new \InvalidArgumentException('non-nullable delivery_time_display cannot be null');
        }
        $this->container['delivery_time_display'] = $delivery_time_display;

        return $this;
    }

    /**
     * Gets delivery_time_range_display
     *
     * @return \OpenAPI\Client\Model\DeliveryTimeRangeDisplay
     */
    public function getDeliveryTimeRangeDisplay()
    {
        return $this->container['delivery_time_range_display'];
    }

    /**
     * Sets delivery_time_range_display
     *
     * @param \OpenAPI\Client\Model\DeliveryTimeRangeDisplay $delivery_time_range_display delivery_time_range_display
     *
     * @return self
     */
    public function setDeliveryTimeRangeDisplay($delivery_time_range_display)
    {
        if (is_null($delivery_time_range_display)) {
            throw new \InvalidArgumentException('non-nullable delivery_time_range_display cannot be null');
        }
        $this->container['delivery_time_range_display'] = $delivery_time_range_display;

        return $this;
    }

    /**
     * Gets inventory_address
     *
     * @return \OpenAPI\Client\Model\BusinessAddress
     */
    public function getInventoryAddress()
    {
        return $this->container['inventory_address'];
    }

    /**
     * Sets inventory_address
     *
     * @param \OpenAPI\Client\Model\BusinessAddress $inventory_address inventory_address
     *
     * @return self
     */
    public function setInventoryAddress($inventory_address)
    {
        if (is_null($inventory_address)) {
            throw new \InvalidArgumentException('non-nullable inventory_address cannot be null');
        }
        $this->container['inventory_address'] = $inventory_address;

        return $this;
    }

    /**
     * Gets is_pay_at_destination
     *
     * @return bool|null
     */
    public function getIsPayAtDestination()
    {
        return $this->container['is_pay_at_destination'];
    }

    /**
     * Sets is_pay_at_destination
     *
     * @param bool|null $is_pay_at_destination Whether the shipping method is pay at destination
     *
     * @return self
     */
    public function setIsPayAtDestination($is_pay_at_destination)
    {
        if (is_null($is_pay_at_destination)) {
            throw new \InvalidArgumentException('non-nullable is_pay_at_destination cannot be null');
        }
        $this->container['is_pay_at_destination'] = $is_pay_at_destination;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


