<?php
/**
 * ErrorEnumTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ErrorEnumTest Class Doc Comment
 *
 * @category    Class
 * @description * &#x60;User is not authenticated.&#x60; - کاربر تأیید هویت نشده است. * &#x60;Order not found.&#x60; - Order not found. * &#x60;Order is not in a state where shipping can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * &#x60;Order is not in a state where packing can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * &#x60;Failed to initiate refund. Please try again later.&#x60; - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * &#x60;Order is expired or cancelled.&#x60; - سفارش منقضی‌شده یا لغو‌شده است. * &#x60;Invalid request origin.&#x60; - Invalid request origin. * &#x60;Digi Express shipping method not found.&#x60; - روش ارسال دیجی اکسپرس یافت نشد. * &#x60;Order address not found.&#x60; - آدرس سفارش یافت نشد. * &#x60;Failed to fetch Digi Express shipping time window options.&#x60; - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * &#x60;Address ID not found.&#x60; - Address ID not found. * &#x60;Failed to cancel shipment.&#x60; - خطا در کنسل کردن مرسوله. * &#x60;Failed to cancel shipment in third party service.&#x60; - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * &#x60;Shipment not found.&#x60; - Shipment not found. * &#x60;Selected shipping method is not eligible for cancellation.&#x60; - Selected shipping method is not eligible for cancellation. * &#x60;DigiExpress shipment is not in cancelable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * &#x60;DigiExpress shipment is not in reviveable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * &#x60;Failed to revive shipment in third party service.&#x60; - Failed to revive shipment in third party service. * &#x60;Selected shipping method is not eligible for revival.&#x60; - Selected shipping method is not eligible for revival.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ErrorEnum"
     */
    public function testErrorEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
